In [68]:
%matplotlib inline
import numpy as np
import pandas as pd
import xarray as xr
from datetime import datetime,timedelta
from matplotlib import pyplot as plt
from netCDF4 import Dataset

In [69]:
ds=Dataset(r'C:\Users\CHAITANYA AGRAWAL\OneDrive - IIT Delhi\Desktop\UNSW\SP_SST.nc')
url="https://raw.githubusercontent.com/sydney-machine-learning/cyclonedatasets/main/SouthIndian-SouthPacific-Ocean/South_pacific_hurricane.csv"
df = pd.read_csv(url, sep=',',error_bad_lines=False)

C:\Users\CHAITANYA AGRAWAL\AppData\Local\Temp\ipykernel_2332\2504426050.py:3: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(url, sep=',',error_bad_lines=False)

In [70]:
time=ds.variables['time'][:]
lat=ds.variables['latitude'][:]
lon=ds.variables['longitude'][:]
sst=ds.variables['sst']
ds['time']

<class 'netCDF4._netCDF4.Variable'>
int32 time(time)
    units: hours since 1900-01-01 00:00:00.0
    long_name: time
    calendar: gregorian
unlimited dimensions:
current shape = (2040,)
filling on, default _FillValue of -2147483647 used

In [71]:
df['Time']=pd.to_datetime(df['Time'],format='%Y%m%d%H')

In [72]:
intial=1900010100
initial_date=pd.to_datetime(intial,format='%Y%m%d%H')
df["diff"]=df['Time']-initial_date

In [73]:
df

,Basin,No. of Cycl,Time,V5,V6,Lat,Lon,Speed(knots),lat_tenth,lon_tenth,diff
0,SP,14,1982-01-25 18:00:00,BEST,0,180S,1541E,25,18.0,154.1,29974 days 18:00:00
1,SP,14,1982-01-26 00:00:00,BEST,0,191S,1548E,25,19.1,154.8,29975 days 00:00:00
2,SP,14,1982-01-26 06:00:00,BEST,0,197S,1557E,25,19.7,155.7,29975 days 06:00:00
3,SP,14,1982-01-26 12:00:00,BEST,0,199S,1567E,30,19.9,156.7,29975 days 12:00:00
4,SP,14,1982-01-26 18:00:00,BEST,0,201S,1578E,35,20.1,157.8,29975 days 18:00:00
...,...,...,...,...,...,...,...,...,...,...,...
12002,SP,27,2019-05-15 18:00:00,BEST,0,118S,1396E,25,11.8,139.6,43598 days 18:00:00
12003,SP,27,2019-05-16 00:00:00,BEST,0,112S,1385E,25,11.2,138.5,43599 days 00:00:00
12004,SP,27,2019-05-16 06:00:00,BEST,0,112S,1374E,20,11.2,137.4,43599 days 06:00:00
12005,SP,27,2019-05-16 12:00:00,BEST,0,109S,1362E,20,10.9,136.2,43599 days 12:00:00
12006,SP,27,2019-05-16 18:00:00,BEST,0,103S,1352E,25,10.3,135.2,43599 days 18:00:00

In [74]:
df['total']=(df['diff'][0]/timedelta(seconds=1))/3600
df['sst']=""

In [75]:
sst=ds.variables['sst'][:]

In [76]:
sst

masked_array(
  data=[[[[301.6700702526542, 301.7013648054404, 301.71379688805405,
           ..., 302.0108807932705, 301.9718697754137,
           301.93071529503743],
          [301.66706940512677, 301.7480922883676, 301.7236568156442,
           ..., 302.02159810586846, 301.98430185802744,
           301.9521499202334],
          [301.7489496733755, 301.72665766317164, 301.63191661980534,
           ..., 302.0254563384037, 301.99116093809016,
           301.9774427779647],
          ...,
          [281.62398007686136, 281.7011447275669, 281.7851684583352,
           ..., 283.923915360391, 283.9959357010495, 284.0263728688278],
          [281.46107692537186, 281.5322398810225, 281.59568637160265,
           ..., 283.7159994959899, 283.8681853348814,
           283.9063389677303],
          [281.38777050720154, 281.4177789824759, 281.48036808804824,
           ..., 283.6238306076471, 283.77558775403475,
           283.84760809469327]],

         [[--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          ...,
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --]]],


        [[[301.6700702526542, 301.7013648054404, 301.71379688805405,
           ..., 302.0108807932705, 301.9718697754137,
           301.93071529503743],
          [301.66706940512677, 301.7480922883676, 301.7236568156442,
           ..., 302.02159810586846, 301.98430185802744,
           301.9521499202334],
          [301.7489496733755, 301.72665766317164, 301.63191661980534,
           ..., 302.0254563384037, 301.99116093809016,
           301.9774427779647],
          ...,
          [281.62398007686136, 281.7011447275669, 281.7851684583352,
           ..., 283.923915360391, 283.9959357010495, 284.0263728688278],
          [281.46107692537186, 281.5322398810225, 281.59568637160265,
           ..., 283.7159994959899, 283.8681853348814,
           283.9063389677303],
          [281.38777050720154, 281.4177789824759, 281.48036808804824,
           ..., 283.6238306076471, 283.77558775403475,
           283.84760809469327]],

         [[--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          ...,
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --]]],


        [[[301.6700702526542, 301.7013648054404, 301.71379688805405,
           ..., 302.0108807932705, 301.9718697754137,
           301.93071529503743],
          [301.66706940512677, 301.7480922883676, 301.7236568156442,
           ..., 302.02159810586846, 301.98430185802744,
           301.9521499202334],
          [301.7489496733755, 301.72665766317164, 301.63191661980534,
           ..., 302.0254563384037, 301.99116093809016,
           301.9774427779647],
          ...,
          [281.62398007686136, 281.7011447275669, 281.7851684583352,
           ..., 283.923915360391, 283.9959357010495, 284.0263728688278],
          [281.46107692537186, 281.5322398810225, 281.59568637160265,
           ..., 283.7159994959899, 283.8681853348814,
           283.9063389677303],
          [281.38777050720154, 281.4177789824759, 281.48036808804824,
           ..., 283.6238306076471, 283.77558775403475,
           283.84760809469327]],

         [[--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          ...,
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --]]],


        ...,


        [[[--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          ...,
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --]],

         [[302.8356851708121, 302.88841434879424, 302.8961308138648,
           ..., 301.9774427779647, 301.9667254653667,
           301.9585803077922],
          [302.8335417082925, 302.9119924365098, 302.86483626107866,
           ..., 301.9791575479804, 301.96072377031186,
           301.94614822517855],
          [302.8815552687315, 302.80439061802593, 302.69293056700684,
           ..., 301.98901747557056, 301.9684402353824,
           301.96158115531966],
          ...,
          [280.04682035494045, 279.942219383984, 279.8650547332785,
           ..., 280.41978283335067, 280.37948573798224,
           280.42535583590166],
          [280.1149824630637, 280.0356743498386, 280.049392509964, ...,
           280.2877455421434, 280.31989747993737, 280.3619093453215],
          [280.12655716066956, 280.0661115176169, 280.0798296777423,
           ..., 280.34347556765294, 280.3747701204391,
           280.41292375328794]]],


        [[[--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          ...,
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --]],

         [[302.8356851708121, 302.88841434879424, 302.8961308138648,
           ..., 301.9774427779647, 301.9667254653667,
           301.9585803077922],
          [302.8335417082925, 302.9119924365098, 302.86483626107866,
           ..., 301.9791575479804, 301.96072377031186,
           301.94614822517855],
          [302.8815552687315, 302.80439061802593, 302.69293056700684,
           ..., 301.98901747557056, 301.9684402353824,
           301.96158115531966],
          ...,
          [280.04682035494045, 279.942219383984, 279.8650547332785,
           ..., 280.41978283335067, 280.37948573798224,
           280.42535583590166],
          [280.1149824630637, 280.0356743498386, 280.049392509964, ...,
           280.2877455421434, 280.31989747993737, 280.3619093453215],
          [280.12655716066956, 280.0661115176169, 280.0798296777423,
           ..., 280.34347556765294, 280.3747701204391,
           280.41292375328794]]],


        [[[--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          ...,
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --],
          [--, --, --, ..., --, --, --]],

         [[302.8356851708121, 302.88841434879424, 302.8961308138648,
           ..., 301.9774427779647, 301.9667254653667,
           301.9585803077922],
          [302.8335417082925, 302.9119924365098, 302.86483626107866,
           ..., 301.9791575479804, 301.96072377031186,
           301.94614822517855],
          [302.8815552687315, 302.80439061802593, 302.69293056700684,
           ..., 301.98901747557056, 301.9684402353824,
           301.96158115531966],
          ...,
          [280.04682035494045, 279.942219383984, 279.8650547332785,
           ..., 280.41978283335067, 280.37948573798224,
           280.42535583590166],
          [280.1149824630637, 280.0356743498386, 280.049392509964, ...,
           280.2877455421434, 280.31989747993737, 280.3619093453215],
          [280.12655716066956, 280.0661115176169, 280.0798296777423,
           ..., 280.34347556765294, 280.3747701204391,
           280.41292375328794]]]],
  mask=[[[[False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          ...,
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False]],

         [[ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          ...,
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True]]],


        [[[False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          ...,
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False]],

         [[ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          ...,
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True]]],


        [[[False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          ...,
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False]],

         [[ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          ...,
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True]]],


        ...,


        [[[ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          ...,
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True]],

         [[False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          ...,
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False]]],


        [[[ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          ...,
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True]],

         [[False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          ...,
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False]]],


        [[[ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          ...,
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True],
          [ True,  True,  True, ...,  True,  True,  True]],

         [[False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          ...,
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False],
          [False, False, False, ..., False, False, False]]]],
  fill_value=-32767)

In [77]:
for index,row in df.iterrows():
    latitude=row['lat_tenth']
    longitude=row['lon_tenth']
    total=row['total']
    
    diff_lat=(lat-latitude)**2
    diff_lon=(lon-longitude)**2
    diff_time=(time-total)**2
    
    
    min_lat=diff_lat.argmin()
    min_lon= diff_lon.argmin()
    min_time=diff_time.argmin()
    
    
    df.loc[index,'sst']=sst[min_time,0,min_lat,min_lon]

In [78]:
df

,Basin,No. of Cycl,Time,V5,V6,Lat,Lon,Speed(knots),lat_tenth,lon_tenth,diff,total,sst
0,SP,14,1982-01-25 18:00:00,BEST,0,180S,1541E,25,18.0,154.1,29974 days 18:00:00,719394.0,302.806534
1,SP,14,1982-01-26 00:00:00,BEST,0,191S,1548E,25,19.1,154.8,29975 days 00:00:00,719394.0,302.752948
2,SP,14,1982-01-26 06:00:00,BEST,0,197S,1557E,25,19.7,155.7,29975 days 06:00:00,719394.0,302.992158
3,SP,14,1982-01-26 12:00:00,BEST,0,199S,1567E,30,19.9,156.7,29975 days 12:00:00,719394.0,302.756806
4,SP,14,1982-01-26 18:00:00,BEST,0,201S,1578E,35,20.1,157.8,29975 days 18:00:00,719394.0,302.882841
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12002,SP,27,2019-05-15 18:00:00,BEST,0,118S,1396E,25,11.8,139.6,43598 days 18:00:00,719394.0,302.444289
12003,SP,27,2019-05-16 00:00:00,BEST,0,112S,1385E,25,11.2,138.5,43599 days 00:00:00,719394.0,302.061467
12004,SP,27,2019-05-16 06:00:00,BEST,0,112S,1374E,20,11.2,137.4,43599 days 06:00:00,719394.0,302.315252
12005,SP,27,2019-05-16 12:00:00,BEST,0,109S,1362E,20,10.9,136.2,43599 days 12:00:00,719394.0,302.124913
12006,SP,27,2019-05-16 18:00:00,BEST,0,103S,1352E,25,10.3,135.2,43599 days 18:00:00,719394.0,302.127056

In [79]:
time[0]

692496

In [80]:
lat[0]

0.0

In [81]:
lon[0]
df

,Basin,No. of Cycl,Time,V5,V6,Lat,Lon,Speed(knots),lat_tenth,lon_tenth,diff,total,sst
0,SP,14,1982-01-25 18:00:00,BEST,0,180S,1541E,25,18.0,154.1,29974 days 18:00:00,719394.0,302.806534
1,SP,14,1982-01-26 00:00:00,BEST,0,191S,1548E,25,19.1,154.8,29975 days 00:00:00,719394.0,302.752948
2,SP,14,1982-01-26 06:00:00,BEST,0,197S,1557E,25,19.7,155.7,29975 days 06:00:00,719394.0,302.992158
3,SP,14,1982-01-26 12:00:00,BEST,0,199S,1567E,30,19.9,156.7,29975 days 12:00:00,719394.0,302.756806
4,SP,14,1982-01-26 18:00:00,BEST,0,201S,1578E,35,20.1,157.8,29975 days 18:00:00,719394.0,302.882841
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12002,SP,27,2019-05-15 18:00:00,BEST,0,118S,1396E,25,11.8,139.6,43598 days 18:00:00,719394.0,302.444289
12003,SP,27,2019-05-16 00:00:00,BEST,0,112S,1385E,25,11.2,138.5,43599 days 00:00:00,719394.0,302.061467
12004,SP,27,2019-05-16 06:00:00,BEST,0,112S,1374E,20,11.2,137.4,43599 days 06:00:00,719394.0,302.315252
12005,SP,27,2019-05-16 12:00:00,BEST,0,109S,1362E,20,10.9,136.2,43599 days 12:00:00,719394.0,302.124913
12006,SP,27,2019-05-16 18:00:00,BEST,0,103S,1352E,25,10.3,135.2,43599 days 18:00:00,719394.0,302.127056

In [82]:
df

,Basin,No. of Cycl,Time,V5,V6,Lat,Lon,Speed(knots),lat_tenth,lon_tenth,diff,total,sst
0,SP,14,1982-01-25 18:00:00,BEST,0,180S,1541E,25,18.0,154.1,29974 days 18:00:00,719394.0,302.806534
1,SP,14,1982-01-26 00:00:00,BEST,0,191S,1548E,25,19.1,154.8,29975 days 00:00:00,719394.0,302.752948
2,SP,14,1982-01-26 06:00:00,BEST,0,197S,1557E,25,19.7,155.7,29975 days 06:00:00,719394.0,302.992158
3,SP,14,1982-01-26 12:00:00,BEST,0,199S,1567E,30,19.9,156.7,29975 days 12:00:00,719394.0,302.756806
4,SP,14,1982-01-26 18:00:00,BEST,0,201S,1578E,35,20.1,157.8,29975 days 18:00:00,719394.0,302.882841
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12002,SP,27,2019-05-15 18:00:00,BEST,0,118S,1396E,25,11.8,139.6,43598 days 18:00:00,719394.0,302.444289
12003,SP,27,2019-05-16 00:00:00,BEST,0,112S,1385E,25,11.2,138.5,43599 days 00:00:00,719394.0,302.061467
12004,SP,27,2019-05-16 06:00:00,BEST,0,112S,1374E,20,11.2,137.4,43599 days 06:00:00,719394.0,302.315252
12005,SP,27,2019-05-16 12:00:00,BEST,0,109S,1362E,20,10.9,136.2,43599 days 12:00:00,719394.0,302.124913
12006,SP,27,2019-05-16 18:00:00,BEST,0,103S,1352E,25,10.3,135.2,43599 days 18:00:00,719394.0,302.127056

In [67]:
df.to_csv("final.csv")