In [28]:
%matplotlib inline
import numpy as np
import pandas as pd
from math import *
import xarray as xr
from datetime import datetime,timedelta
from matplotlib import pyplot as plt
from netCDF4 import Dataset

In [29]:
ds=Dataset(r'C:\Users\CHAITANYA AGRAWAL\OneDrive - IIT Delhi\Desktop\UNSW\SP_SST.nc')
df=pd.read_csv('South Pacific.csv')

In [30]:
df=df.drop(columns='Unnamed: 0')

In [31]:
for index,row in df.iterrows():
    sub=0
    for weeks in range(1,5):
        sum1=0
        for days in range(1,8):
            sub+=1
            su=str(sub)
            sum1+=df[su][index]
            
        sum1=sum1/7
        s='Week'+'_'+ str(weeks)+'_'+ 'Mean'
        df.loc[index,s]=sum1

In [32]:
for index,row in df.iterrows():
    sub1=0
    sub2=0
    for weeks in range(1,5):
        sum1=0
        sum2=0
        for days in range(1,8):
            sub1+=1
            su=str(sub1)
            sum1+=df[su][index]
            
        sum1=sum1/7
        for days in range(1,8):
            sub2+=1
            su=str(sub2)
            sum2+=(df[su][index]-sum1)*(df[su][index]-sum1)
        sum2=sum2/7
        s='Week'+'_'+ str(weeks)+'_'+ 'SD'
        df.loc[index,s]=sqrt(sum2)

In [33]:
dict={0:[],1:[],2:[],3:[],4:[],5:[],6:[],7:[],8:[],9:[],10:[],11:[],12:[],13:[],14:[],15:[],16:[],17:[],18:[],19:[],20:[],21:[],22:[],23:[],24:[],25:[],26:[],27:[],28:[],29:[],30:[],31:[],32:[],33:[],34:[],35:[],36:[],37:[],38:[],39:[],40:[]} 
for index,row in df.iterrows():
    add=dict[df["No. of Cycl"][index]]
    add.append(df["Speed(knots)"][index])

In [34]:
df.sort_values(["No. of Cycl"],axis=0, ascending=True,inplace=True,na_position='first')
df

,Basin,No. of Cycl,Time,V5,V6,Lat,Lon,Speed(knots),lat_tenth,lon_tenth,...,29,30,Week_1_Mean,Week_2_Mean,Week_3_Mean,Week_4_Mean,Week_1_SD,Week_2_SD,Week_3_SD,Week_4_SD
7110,SP,1,2006-10-25 06:00:00,BEST,0,157S,1717E,60,15.7,171.7,...,302.873410,302.873410,303.112498,303.207668,302.159882,301.809273,0.025882,0.106031,0.578168,0.691800
3868,SP,1,1994-11-10 18:00:00,BEST,0,71S,1677E,15,7.1,167.7,...,302.875125,302.641916,302.442758,302.599047,302.868266,302.547726,0.068705,0.046228,0.592838,0.463783
3869,SP,1,1994-11-11 00:00:00,BEST,0,76S,1679E,15,7.6,167.9,...,302.914136,302.678784,302.453720,302.611112,302.847137,302.544787,0.071405,0.046150,0.614468,0.479597
3870,SP,1,1994-11-11 06:00:00,BEST,0,81S,1682E,15,8.1,168.2,...,302.935999,302.696360,302.450474,302.603824,302.823376,302.536642,0.068705,0.046555,0.641754,0.500696
3871,SP,1,1994-11-11 12:00:00,BEST,0,86S,1686E,20,8.6,168.6,...,302.942430,302.725940,302.474052,302.620910,302.811740,302.537070,0.063455,0.048532,0.666539,0.515404
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4920,SP,38,1997-06-08 12:00:00,BEST,0,87S,1730W,25,8.7,173.0,...,301.085762,300.984162,302.760235,302.966314,302.062079,301.729536,0.199515,0.302515,0.196474,0.132422
4922,SP,38,1997-06-09 00:00:00,BEST,0,85S,1738W,25,8.5,173.8,...,301.046751,300.997023,302.697279,302.999201,302.067468,301.773324,0.217516,0.296679,0.189433,0.154836
4923,SP,38,1997-06-09 06:00:00,BEST,0,83S,1742W,30,8.3,174.2,...,300.966586,300.964014,302.603211,302.875431,302.048606,301.800576,0.198165,0.278512,0.201733,0.143384
4914,SP,38,1997-06-07 00:00:00,BEST,0,91S,1711W,15,9.1,171.1,...,300.877847,300.891565,302.636221,302.881923,302.145735,301.687157,0.183464,0.175685,0.299335,0.108076
4946,SP,38,1997-06-15 00:00:00,BEST,0,195S,1667W,40,19.5,166.7,...,301.298823,301.524315,302.578898,302.803227,302.335891,302.031458,0.000000,0.091260,0.216527,0.181542

In [36]:
df['Avg_Wind_speed']=""
df['Deviation_Wind_speed']=""
for i in range(1,39):
    c=0
    d=0
    if(len(dict[i])!=0):
        for j in range(0,len(dict[i])):
            c=c+dict[i][j]
            d=d+dict[i][j]*dict[i][j]
        c=c/len(dict[i])
        d=d/len(dict[i])
        for index,row in df.iterrows():
            if(df['No. of Cycl'][index]==i):
                df.loc[index,'Avg_Wind_speed']=c
                df.loc[index,'Deviation_Wind_speed']=sqrt(d-c*c)
                break

In [37]:
df = df.reset_index(drop=True)

In [42]:
df.to_csv("SP_with_Mean_nd_Dev.csv")